version: "3.6"
services:
  tomcat:
      image: tomcat:9.0

      ports:
        - "8080:8080"

      volumes:
        # '.tomCatStuff/tomcat-users.xml:/opt/bitnami/tomcat/conf/tomcat-users.xml:rw'
        #- './context.xml:/usr/local/tomcat/conf/Catalina/localhost/manager.xml:rw'
        #- './manager.xml:/usr/local/tomcat/conf/Catalina/localhost/host-manager.xml:rw'
        - './CreamaLaunchBay:/usr/local/tomcat/webapps/'
        #- '.[project_folder_path]:/usr/local/tomcat/webapps/myproject'
  mysqldataBase:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      cap_add:
        - SYS_NICE  # CAP_SYS_NICE
      environment:
        MYSQL_ROOT_PASSWORD: callme
        MYSQL_USER: cremauser
        MYSQL_PASSWORD: callme
        MYSQL_DATABASE: db_crema
      ports:
        - "3306:3306"


  node:
    image: "node:14"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - '../crema-react:/home/node/app'
    ports:
      - "3000:3000"
    command: "npm start"

